### ISSUE TITLE
Instance not showing up after installation

### ISSUE THREAD

**Issue by SebastianHanz** [tim2zg/ioBroker.fronius-wattpilot#1]
I installed the Adapter via expert-mode later also via npm - same result.
Installation process seems to work fine see log but iobroker does not create a new instance.
Any idea what went wrong here?

Thank you!

**Logfile**  
iobroker url https://github.com/tim2zg/ioBroker.fronius-wattpilot --host raspberrypi --debug
iobroker install tim2zg/ioBroker.fronius-wattpilot#328da7ec3ddc3daf6ea47d4f4874c7957cca936a
iobroker NPM version: 8.15.0
iobroker Installing tim2zg/ioBroker.fronius-wattpilot#328da7ec3ddc3daf6ea47d4f4874c7957cca936a... (System call)
iobroker npm WARN skipping integrity check for git dependency ssh://git@github.com/tim2zg/ioBroker.fronius-wattpilot.git 
iobroker added 4 packages, and changed 1 package in 9s98 packages are looking for funding  run `npm fund` for details
iobroker upload [3] fronius-wattpilot.admin /opt/iobroker/node_modules/iobroker.fronius-wattpilot/admin/fronius-wattpilot.png fronius-wattpilot.png image/png
iobroker upload [2] fronius-wattpilot.admin /opt/iobroker/node_modules/iobroker.fronius-wattpilot/admin/index_m.html index_m.html text/html
iobroker upload [1] fronius-wattpilot.admin /opt/iobroker/node_modules/iobroker.fronius-wattpilot/admin/style.css style.css text/css
iobroker upload [0] fronius-wattpilot.admin /opt/iobroker/node_modules/iobroker.fronius-wattpilot/admin/words.js words.js application/javascript
iobroker exit 0`

**Versions:**  
 - Adapter version: 2.2.2
 - JS-Controller version: 4.0.23
 - Node version: v16.17.0
 - NPM version: 8.15.0
 - Operating system: RaspberryPi OS 64Bit Lite

**Comment by tim2zg** [comment]
If you install an adapter through the expert mode, it only gets added to your adapter list. You have to refresh the Adapter Page to see the Adapter and then install it from there again. 

Hope this helps.

Best regards,
Tim

**Comment by SebastianHanz** [comment]
Too blind to see...
Thank you very much!
