### ISSUE TITLE
Idea: Possibility to give a list of additional datapoints

### ISSUE THREAD

**Issue by derHaubi** [tim2zg/ioBroker.fronius-wattpilot#23]
Hi and first of all thanks for the great work :)

Would it be possible to have a textfield in within the Instance Admin-Page, to give a comma-seperated list of additinal datapoints to be used.
Currently we see either the "most common" ones or all. It would be great to have the possibility to give a list of additional point like for me currently I'am only missing "frc" and "acs".

My suggestion would be a textfield to give additional Datapoints comma seperated, e.g

frc,acs,...

Thanks in advance

Peter

**Comment by tim2zg** [comment]
Done!
