### ISSUE TITLE
No update for Common data

### ISSUE THREAD

**Issue by tipp88** [tim2zg/ioBroker.fronius-wattpilot#26]
If the adapter config switch "only common data" is deactivated, then the adapter gets all available API fields, but the common data fields like Power, Amp1/Amp2/Amp3 are no longer updated...

**Comment by tim2zg** [comment]
“It’s a bug not a feature”, well mostly. If you start with the normal parser and switch to the other one, it will no longer update the states created before, your states are still but the name changed. I still can change it if it is wished.

**Comment by tipp88** [comment]
You don't need to change just for me. I found the option to include more properties in the common data request. That is all I need.

**Comment by tim2zg** [comment]
Under development on the testing branch.

**Comment by tim2zg** [comment]
New version out.
