### ISSUE TITLE
"Give additional Parameters" does not work any longer

### ISSUE THREAD

**Issue by tipp88** [tim2zg/ioBroker.fronius-wattpilot#29]
Seit dem letzten Update funktioniert die Option "Give additional Parameters" nicht mehr.
v4.5.0
Zuletzt mit V4.3.0 lief die Einstellung noch
 
![image](https://user-images.githubusercontent.com/68737433/222112375-1ecc43bb-af10-4bde-b793-9d0ad9f2057b.png)

![image](https://user-images.githubusercontent.com/68737433/222112356-dcb59e2e-834d-4171-94de-2a0fc84f365d.png)

**Comment by tipp88** [comment]
DP löschen und Instanz neustarten erstellt zwar den DP wieder mit korrekten Wert, aber es erfolgt dann kein Update mehr bis er wieder gelöscht wird.

**Comment by tim2zg** [comment]
Issue reproduced and Bug found.

**Comment by tim2zg** [comment]
Fixed with #30 and version 4.5.1
