### ISSUE TITLE
Zugriffsverwaltung - Authentifizierung auslesbar

### ISSUE THREAD

**Issue by Bender275** [tim2zg/ioBroker.fronius-wattpilot#31]
Hallo,

und auch gleich sorry im voraus, falls ich es übersehe.
Aber ist es möglich, Werte der Zugriffsverwaltung auszulesen und /oder zu schreiben?
Zum Beispiel kann die Authentifizierung offen oder notwendig sein. Wenn ich den Wert ändere, ändert sich aber nichts an den vorhandneneDatenpunkten im ioBroker.
Bei AccessState wird immer "open" angezeigt.

Viele Grüße
Bender275

**Comment by tim2zg** [comment]
Hallo,
Du kannst die acs brauchen, um die Zugriffsverwaltung auszulesen. Musst du gegeben falls als zusätzlicher Parameter in die Adapter config eintragen. Danach kannst du set_state verwenden, um sie zu steuern. https://github.com/tim2zg/ioBroker.fronius-wattpilot#set-states 
Freundliche Grüße,
Tim
