### ISSUE TITLE
Please fix issues reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [tim2zg/ioBroker.fronius-wattpilot#37]
[E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
[W171] "common.title" is deprecated in io-package.json
[W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
[W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)

https://www.iobroker.dev/adapter-check

**Comment by tim2zg** [comment]
Done!
