### ISSUE TITLE
Errorstatus, Power1, carConnected

### ISSUE THREAD

**Issue by Norb1204** [tim2zg/ioBroker.fronius-wattpilot#40]
I found some errors in the code for ErrorStatus, carConnected and Power1.
I made some changes in the code (Errorstatus, carConnected) to get also more information. 

I have attached the code, can you please check if this is OK. I test it without errors.
Maybe you can compare the code and see the differences I have made. I hope this is OK for you when I have changed the code and send it to you.
[main.zip](https://github.com/tim2zg/ioBroker.fronius-wattpilot/files/12346279/main.zip)

**Comment by tim2zg** [comment]
Hallo,
Vielen Dank für deine Verbesserungen, ich habe einige Fehler gemacht, welche ich nicht gesehen habe, danke fürs Fixen. Das nächste Mal kannst du auch einen Pull Request machen, dann geht es etwas einfacher. Ich habe deinen Code eingebaut und er sollte ab jetzt in Version 4.6.2 verfügbar sein. Nochmals vielen Dank, beste Grüsse
Tim
