### ISSUE TITLE
Zeigt keinen Status AllowCharging an

### ISSUE THREAD

**Issue by Norb1204** [tim2zg/ioBroker.fronius-wattpilot#43]
Hallo,

bitte AllowCharging überprüfen, zeigt keinen korrekten Status an.
Ich habe das Temporär so gelöst siehe Anhang.
Gruß
Norbert

![alw_change_1](https://github.com/tim2zg/ioBroker.fronius-wattpilot/assets/132662785/c3dc3ea3-5877-420e-8f72-febab5c2f35f)
![alw_change_2](https://github.com/tim2zg/ioBroker.fronius-wattpilot/assets/132662785/3965d9c8-f07f-4d20-90c3-c704b34b5acc)

**Comment by tim2zg** [comment]
danke dir, läuft in 4.6.3
