### ISSUE TITLE
Connection to Wattpilot not possible

### ISSUE THREAD

**Issue by TobiLanger** [tim2zg/ioBroker.fronius-wattpilot#44]
Hi,

I tried to setup ioBroker with Fronius-Wattpilot adapter.
After setting Serialnumber, password, interval 10s and Cloud usage
I can only get - Host connected, alive, but no connection with the device.
The logs say: "Please check your host! Seams like your host is Offline, attempt to reconnect in 2.5 minutes"

Can you help please?

![1](https://github.com/tim2zg/ioBroker.fronius-wattpilot/assets/43041516/88ad6a84-96dd-4a31-8965-357749f6a9a2)
![2](https://github.com/tim2zg/ioBroker.fronius-wattpilot/assets/43041516/e14fb06e-9100-4208-a50d-b086f6ffad6d)
![3](https://github.com/tim2zg/ioBroker.fronius-wattpilot/assets/43041516/0237de8e-73c8-4226-814f-ec39c3526122)

Thanks, Tobi

**Comment by Bender275** [comment]
Hi, do you really want to use it via Cloud? Otherwise just enter the local IP, is that working?
BR,
Bender

**Comment by TobiLanger** [comment]
Hi again.
My first try to that project was outside my LAN, so I tried over cloud.
Yesterday in the evening I tried to connect from inside my LAN.
This works perfekt. In the end, I only want to use it from inside my LAN ;-)
Thank you.
Tobi

**Comment by tim2zg** [comment]
this is a bug

**Comment by tim2zg** [comment]
fixed in 4.6.3
