### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by Norb1204** [tim2zg/ioBroker.fronius-wattpilot#55]
In der aktuellen Version 4.6.3 gibt es scheinbar ein memory leak. Der reservierte Arbeitsspeicher steigt ständig an. In 5 Tagen von ca. 80 MB auf 126 MB.

Ist zuerst mal kein Problem, starte den Adapter regelmäßig neu.

**Comment by tim2zg** [comment]
Hallo,

das ist ganz normal. Der Adapter braucht, wenn er vollständig initialisiert ist, ca. 128 MB RAM. Warum nicht gleich am Anfang? Der Adapter empfängt alle Werte vom Wattpilot, auch jene, die nur alle paar Stunden oder Tage kommen. Das heißt, er legt erst dann die entsprechenden Werte und Objekte an. Deswegen kann es gut sein, dass der Arbeitsspeicher über eine Woche anwächst. Er sollte jedoch nicht über ca. 128 – 135 MB hinauswachsen.

Beste Grüße
